version: "3.7"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    networks:
      - peopleflow
    ports:
      - 127.0.0.1:2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    networks:
      - peopleflow
    ports:
      - 127.0.0.1:9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: docker.io/bitnami/redis:6.2
    networks:
      - peopleflow
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 127.0.0.1:6379:6379

  peopleflow:
    build:
      context: .
    container_name: peopleflow
    networks:
      - peopleflow
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:18080:18080
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:18080"
      - CONFIG_LOCATION=classpath:/

networks:
  peopleflow:
