kafka:
  bootstrap-servers: "127.0.0.1:9093"
  topic: "test"
  group: "sample-group"
logging:
  level:
    ROOT: info

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    path: /swagger-ui